name: Deploy to Amazon EC2

on:
  push:
    branches: 
      - main

env:
  AWS_REGION: MY_AWS_REGION
  DOCKERHUB_USERNAME: vaishnavi639
  IMAGE_NAME: todo

permissions:
  contents: read

jobs:
  deploy:
    name: Deploy
    runs-on: self-hosted
    environment: production

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Log in to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build, tag, and push image to DOCKERHUB
      id: build-image
      env:
        IMAGE_TAG: ${{ github.sha }}
      run: |
        IMAGE=$DOCKERHUB_USERNAME/$IMAGE_NAME:$IMAGE_TAG
        docker build -t $IMAGE .
        docker push $IMAGE
        echo "image=$IMAGE" >> $GITHUB_OUTPUT

    - name: Pull the Image & Run the Image
      run: |
        IMAGE=${{ steps.build-image.outputs.image }}
        docker pull $IMAGE
        docker ps -q --filter ancestor=$IMAGE | xargs -r docker stop
        docker ps -a -q --filter ancestor=$IMAGE | xargs -r docker rm
        docker run -d -p 5000:5000 $IMAGE
